### ISSUE TITLE
Pop up not showing, dictionary entries not showing in manual search

### ISSUE THREAD

**Issue by teksongeap** [Samuihasu/krdict-yomichan#1]
What settings were you using?

**Comment by ProgramComputer** [comment]
You can highlight/lookup and manual search on Korean words. You'll need a separate reverse dictionary for English to Korean.

**Comment by teksongeap** [comment]
That wasn't even my question, I don't know how you thought I was asking for English to Korean. The problem is that it doesn't work for me, neither the highlight/lookup or the manual search on Korean words. Nothing. Zilch. I'm using Chrome but for Mozilla it works fine.

**Comment by Samuihasu** [comment]
Sounds like you have an issue with Yomichan itself and not the dictionary. Maybe post your questions here: https://github.com/FooSoft/yomichan

**Comment by ProgramComputer** [comment]
Look at the instructions at https://foosoft.net/projects/yomichan/index.html#basic-usage . For highlighting, by default, press shift and hover over the korean word, and yomichan should highlight.
