### ISSUE TITLE
Problem with ㅂ 받침 adjectives 

### ISSUE THREAD

**Issue by Sentoss** [Samuihasu/krdict-yomichan#3]
It seems like there's a missing entry/conjugation throughout the dictionary, which is the lack of ㅂ irregular verbs' adjective form, such as 어두운 for 어둡다, or 어려운 for 어렵다.
Examples:

verb: 부드러운
Dictionary form: 부드럽다
Definition: soft; tender
issue: the adjective form doesn't get detected; it's not in the dictionary.

verb: 어려운
Dictionary form: 어렵다
Definition: difficult
Issue: the adjective form doesn't get detected; it's not in the dictionary.

verb: 어두운
Dictionary form: 어둡다
Definition: dark; dim
Issue: the adjective form doesn't get detected; it's not in the dictionary.

Can you add these to the file and update it?

Thank you for the great work!

**Comment by Samuihasu** [comment]
Do you only want these 3 added or wait for a longer list? I'm no longer learning Korean so don't know all the ㅂ irregular verbs

**Comment by Sentoss** [comment]
hmm....I want it to be done to all verbs that are irregular, and there's a way to algorithmically do this if you have condition checking.

The ㅂ irregular verbs get their ㅂ changed (to 우) when they're conjugated with 아/어요 which is already in the dictionary (I checked the verbs I suggested). So, what you can do is: check if the verb ends with a ㅂ and check if its ㅂ changes when conjugated with 아/어요 and then, if that's the case, add the new form to the verb.

Is this feasible with excel/google sheets?

**Comment by Sentoss** [comment]
Ok, so I assumed that it might not work (I'm not an excel expert), and I tried creating a python script that will automate this whole process.

It kinda worked (the detection part was a complete success, and the modification part), but I faced problems when outputting and exporting to yomichan.

I also noticed in the other issue you mentioning that: you simply export the excel as a .txt then rename it to .json. 

I don't really understand how this works, but if exporting in this manner to json works, if you want, I can send you an updated version of the script that searches and modifies the excel sheet and outputs xlsx file. Only thing remaining would be for you to make it json.

**Comment by Samuihasu** [comment]
I can try the script. Would the script require all the data to be on one sheet and not multiple sheets in the excel file?

**Comment by Sentoss** [comment]
I mean, it would be easier to put each sheet in a new file, so that it's similar to the .json files (regular naming. i.e "term_bank_x.json"). Otherwise, I might need to edit the script.

**Comment by Sentoss** [comment]
Ok, @Samuihasu this is the script. I needed to edit it a little bit cause I faced some trouble. If you face any problems running it, just mention me here.
https://pastebin.com/W0Ep8EA3 (click download)

**Comment by Samuihasu** [comment]
opps wait missed a few verbs

**Comment by Samuihasu** [comment]
Okay. Now it should be good. Reopen if you see any issues.

https://github.com/Samuihasu/krdict-yomichan/releases/tag/v2

**Comment by Sentoss** [comment]
Ok, sorry to bother you with this again, but the script missed 돕다 because it's an irregular among irregulars (instead of being 도워 it's conjugated as 도와) and hence, wasn't detected.
please add it, it's

verb: 도운
Dictionary form: 돕다
Definition: to help
Issue: the adjective form doesn't get detected; it's not in the dictionary.

Thanks for your help!

**Comment by Samuihasu** [comment]
Added it.
